[tool.mypy]
explicit_package_bases = true
files = ["trio_websocket", "tests", "autobahn", "examples"]
show_column_numbers = true
show_error_codes = true
show_traceback = true
disallow_any_decorated = true
disallow_any_unimported = true
ignore_missing_imports = true
local_partial_types = true
no_implicit_optional = true
strict = true
warn_unreachable = true
